rankalist_web/apps/rankalist/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template

urlpatterns = patterns('rankalist.views',
    url(r'^$', "home", name="home"),
    url(r'^thanks$', "thanks", name="thanks"),
    url(r'^confirm/(?P<list_id>.+)$', "confirm", name="confirm"),
    url(r'^vote/(?P<list_id>.+)$', "vote", name="vote"),
    url(r'^results/(?P<list_id>.+)$', "results", name="results"),            
    url(r'^robots.txt', direct_to_template, {'template': 'robots.txt'}),
)

rankalist_web/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rankalist_web.views.home', name='home'),
    # url(r'^rankalist_web/', include('rankalist_web.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include("rankalist.urls")),
    url(r'^favicon.ico', 'django.views.generic.simple.redirect_to', {'url': 'https://s3.amazonaws.com/projectite-cdn/favicon.ico'} ),    
)

rankalist_web/apps/rankalist/models.py
from django.db import models

# Create your models here.
class List( models.Model ):
    key = models.CharField(max_length=8)
    adminKey = models.CharField(max_length=8)
    instructions = models.CharField(max_length=512)

class ListItem(models.Model):
    related_list = models.ForeignKey(List, related_name="items")
    text = models.CharField(max_length=256)
    class Meta:
        ordering = ('-id',)
        
class Voter(models.Model):
    name = models.CharField(max_length=128)
    related_list = models.ForeignKey(List, related_name="voters")

class Vote(models.Model):
    related_list = models.ForeignKey(List, related_name="votes")
    item = models.ForeignKey(ListItem, related_name="votes")
    voter = models.ForeignKey(Voter, related_name="votes")
    rank = models.IntegerField(default=0)
    class Meta:
        ordering = ('rank',)

rankalist_web/apps/rankalist/forms.py
from django import forms
from django.core.urlresolvers import reverse


class ListForm(forms.Form):    
    instructions = forms.CharField(widget=forms.Textarea,initial="Please rank these items in order of importance.", help_text="Anyone ranking this list will see these instructions.")
    items = forms.CharField(widget=forms.Textarea,help_text="Enter one item per line.")

class RankForm(forms.Form):
    name = forms.CharField()

rankalist_web/apps/rankalist/views.py
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.conf import settings
import random
import string
import logging

from models import *
from forms import *


logger = logging.getLogger(__name__)

def results(request, list_id):
    l = List.objects.get(adminKey=list_id)
    items = []
    for item in l.items.all():
        total = 0
        count = 0
        for vote in item.votes.all():
            total += vote.rank
            count += 1

        if count > 0:
            items.append( (total, item) )
    items.sort(key=lambda a: a[0])
    items = [i[1] for i in items]
    return render_to_response("rankalist/results.html", { "averages":items, "list":l },
                                                 context_instance=RequestContext(request))

def vote(request, list_id):
    l = List.objects.get(key = list_id)

    if request.method == "POST":
        form = RankForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            orders = request.POST.get("orders")
            orders = orders.split(" ")
            
            voter = Voter(related_list=l, name=name)
            voter.save()
            
            rank = 0
            for order in orders:        
                if order == "":
                    continue
                rank += 1
                listItem = ListItem.objects.get(id=order)
                if listItem.related_list == l:
                    v = Vote(related_list=l, voter=voter, rank=rank, item=listItem)
                    v.save()                
            return HttpResponseRedirect("%s?key=%s" % (reverse('thanks'), l.key ))
    else:
        form = RankForm()
    return render_to_response("rankalist/vote.html", { "form":form, "list":l },
                                                 context_instance=RequestContext(request))
def thanks(request):
    return render_to_response("rankalist/thanks.html",  context_instance=RequestContext(request))

# def clone(request, list_id):
    
    
    
def home(request):
    if request.method == "POST":
        form = ListForm(request.POST)
        if form.is_valid(): # All validation rules pass
            k, ak = _generateKeys()
            l = List(key=k, adminKey=ak, instructions=form.cleaned_data['instructions'])
            l.save()
            items = form.cleaned_data['items'].splitlines()
            items.reverse()
            for item in items:
                li = ListItem(related_list=l, text=item)
                li.save()                
            
            return HttpResponseRedirect(reverse('confirm',args=[l.adminKey]))
    else:
        form = ListForm()
    return render_to_response("rankalist/home.html", { "form":form },
                                                              context_instance=RequestContext(request))

def _generateKeys():
    ak = ''.join(random.choice(string.letters + string.digits) for i in xrange(8))
    k = ''.join(random.choice(string.letters + string.digits) for i in xrange(8))
    try:
        List.objects.get(key=k, adminKey=ak)
    except:
        return (k, ak)
    return _generateKeys()
    

def confirm(request, list_id):
    l = List.objects.get(adminKey = list_id)
    return render_to_response("rankalist/confirm.html", { 'list':l },
                                                              context_instance=RequestContext(request))
    

rankalist_web/apps/rankalist/templates/rankalist/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Rankalist - What's more important?</title>
    <meta name="description" content="Use relative ranking to get decisions made">
    <meta name="author" content="Marc Hughes">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

	<link rel="stylesheet" href="{{STATIC_URL}}bootstrap.min.css" type="text/css" media="screen, projection">
    <link rel="stylesheet" href="{{STATIC_URL}}site.css" type="text/css" media="screen, projection">

	<script src="{{STATIC_URL}}jquery.min.js" type="text/javascript"></script>
	<script src="{{STATIC_URL}}jquery-ui.min.js" type="text/javascript"></script>	

    <style type="text/css">
      /* Override some defaults */
      html, body {
        background-color: #eee;
      }
      body {
        padding-top: 40px; /* 40px to make the container go all the way to the bottom of the topbar */
      }
      .container > footer p {
        text-align: center; /* center align it with the container */
      }
      .container {
        width: 820px; /* downsize our container to make the content feel a bit tighter and more cohesive. NOTE: this removes two full columns from the grid, meaning you only go to 14 columns and not 16. */
      }

      /* The white background content wrapper */
      .container > .content {
        background-color: #fff;
        padding: 20px;
        margin: 0 -20px; /* negative indent the amount of the padding to maintain the grid system */
        -webkit-border-radius: 0 0 6px 6px;
           -moz-border-radius: 0 0 6px 6px;
                border-radius: 0 0 6px 6px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
                box-shadow: 0 1px 2px rgba(0,0,0,.15);
      }

      /* Page header tweaks */
      .page-header {
        background-color: #f5f5f5;
        padding: 20px 20px 10px;
        margin: -20px -20px 20px;
      }

      /* Styles you shouldn't keep as they are for displaying this base example only */
      .content .span10,
      .content .span4 {
        min-height: 500px;
      }
      /* Give a quick and non-cross-browser friendly divider */
      .content .span4 {
        margin-left: 0;
        padding-left: 19px;
        border-left: 1px solid #eee;
      }

      .topbar .btn {
        border: 0;
      }

    </style>
	{% block extra_head %}{% endblock %}
  </head>

  <body>

    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="/">Rank a list</a>
<!--          <form action="" class="pull-right">
            <input class="input-small" type="text" placeholder="Username">
            <input class="input-small" type="password" placeholder="Password">
            <button class="btn" type="submit">Sign in</button>
          </form>
-->
        </div>
      </div>
    </div>

    <div class="container">

      <div class="content">
        <div class="page-header">
		{% block pageheader %}
          <h1>Rank a list <small></small></h1>
		{% endblock %}
        </div>
        <div class="row">
          <div class="span10">
            {% block maincontent %}<h2>Main content</h2>
			{% endblock %}
          </div>
          <div class="span4">
	        {% block secondarycontent %}<h3>Secondary content</h3>
			{% endblock %}            
          </div>
        </div>
      </div>

      <footer>
		<hr />
		<center>
		<!-- AddThis Button BEGIN -->
		<div class="addthis_toolbox addthis_default_style addthis_32x32_style" style="width: 400px; margin: 0 auto;">
		<a class="addthis_button_preferred_1"></a>
		<a class="addthis_button_preferred_2"></a>
		<a class="addthis_button_preferred_3"></a>
		<a class="addthis_button_digg"></a>
		<a class="addthis_button_google_plusone"></a>
		<a class="addthis_button_compact"></a>
		<a class="addthis_counter addthis_bubble_style"></a>
		</div>
		<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4e962b1e4c0ce05f"></script>
		<!-- AddThis Button END -->

		<br/><br/>
		</center>
		<p>Sponsored by <a href="http://www.scrumdo.com/">ScrumDo</a> - the popular <a href="http://www.scrumdo.com/">scrum tool</a></p>
        <p>&copy; Rogue Software Development LLC 2012</p>
      </footer>

    </div> <!-- /container -->
	<script type="text/javascript">
	  var _gauges = _gauges || [];
	  (function() {
	    var t   = document.createElement('script');
	    t.type  = 'text/javascript';
	    t.async = true;
	    t.id    = 'gauges-tracker';
	    t.setAttribute('data-site-id', '50060fd9613f5d1777000003');
	    t.src = '//secure.gaug.es/track.js';
	    var s = document.getElementsByTagName('script')[0];
	    s.parentNode.insertBefore(t, s);
	  })();
	</script>
  </body>
</html>

rankalist_web/apps/rankalist/templates/rankalist/confirm.html
{% extends "rankalist/base.html" %}
{% load uni_form_tags %}


{% block topbar %}{% endblock %}

{% block secondarycontent %}
<h3>Wasn't that easy?</h3>
<p>Now that you've created your list, you can send the "Vote URL" to people whom you want to vote on the list.  Save the "Results URL" for yourself so you can see how they voted.</p>
{% endblock %}

{% block pageheader %}
  <h1>You're all set!</h1>
{% endblock %}

{% block maincontent %}

	
  <div class="alert-message block-message success span9">
	<strong>Well Done!</strong>  You created your list.  Now, make sure to make a note of the two urls below.  Since we don't make you sign up for an
	account, you'll need them to access this list later.
  </div>

  <div class="alert-message block-message info span9">
	<h3>Vote URL</h3>
    Send this URL to anyone you want to rank your list:<br/>
	<a href="{% url vote list.key %}">http://www.rankalist.com{% url vote list.key %}</a>
  </div>

  <div class="alert-message block-message info span9">
	<h3>Results URL</h3>
    Send this URL to anyone you want to see the results of the ranking:<br/>
	<a href="{% url results list.adminKey %}">http://www.rankalist.com{% url results list.adminKey %}</a>
  </div>


  
{% endblock %}

rankalist_web/apps/rankalist/templates/rankalist/home.html
{% extends "rankalist/base.html" %}
{% load uni_form_tags %}


{% block topbar %}{% endblock %}

{% block pageheader %}<h1>Create a list <small>get rankings</small></h1>{% endblock %}

{% block secondarycontent %}
<h3>What is this?</h3>
<p>Ever get told that three different things are top priority?  Ever ask for a list to be ranked only to get it back
	 and every item except one is marked "high", the other being "critical"?  Need business input in ranking your backlog?
</p>
<p>
	I think we can help.
</p>
<h3>How do I get started?</h3>
<p>
	Enter the items you want ranked in the "items" field on the left, one per line.  We'll give you a URL you can send around that lets people
  rank the items, but forces an absolute ordering between them.  
</p>
<p>
	Want to <a href="http://www.rankalist.com/vote/UuynM0q3">see an example</a> of what it's like to rank a list?
</p>
<p>
	 It's super simple, no signing up.  No passwords.
</p>
<h3>Is that secure?</h3>
<p>
	 The URL generated is private for you and secured with a randomized token.  
	 We don't let web crawlers see them.  So as long as you don't post it publicly, it's safer than guessable 
	 passwords that most people pick.
</p>
{% endblock %}

{% block maincontent %}
  <form method="POST" action="">          
       <fieldset>
           <div id="div_id_instructions" class="clearfix">

				<label for="id_instructions" class="requiredField">Instructions</label> 
				<div class="input">
				<textarea id="id_instructions" rows="3" cols="40" name="instructions" class="textarea span7">Please rank these items in order of importance.</textarea>
				<span class="help-block">
					Anyone ranking this list will see these instructions.
				</span>
				</div>
			
			<br/>
			<div id="div_id_items" class="ctrlHolder">
				<label for="id_items" class="requiredField">Items</label> 
				<div class="input">
				<textarea id="id_items" rows="15" cols="40" name="items" class="textarea span7"></textarea>
				<span class="help-block">
					Enter one item per line.
				</span>

				</div>
			</div>

		   {% csrf_token %}            
          <input type="hidden" name="action" value="create" />               
          <div class="actions">
            <input type="submit" class="btn primary" value="Create List">
          </div>
       </fieldset>                        
   </form>
  


{% endblock %}

rankalist_web/apps/rankalist/templates/rankalist/results.html
{% extends "rankalist/base.html" %}
{% load uni_form_tags %}


{% block topbar %}{% endblock %}

{% block pageheader %}<h1>Results</h1>{% endblock %}

{% block secondarycontent %}
<h3>Waiting for results...</h3>
<p>As people fill out your ranking, their results will fill up here.  </p>
<p>In case you forgot, the vote url is:<br><small><a href="{% url vote list.key %}">http://www.rankalist.com{% url vote list.key %}</a></small></p>

<h3>Create another list</h3>
Want to create another list?<br/>
<br/>
<center><a href="/" class="btn success">Create another list</a></center>

<br/><br/>
<h3>Do you Scrum?</h3>
Then check out <a href="http://www.scrumdo.com/">ScrumDo</a>, an agile project management website.


{% endblock %}

{% block maincontent %}
<div class="resultsBody">

<p>{{ list.instructions }}</p>

<h3>Average Rankings:</h3>
<ol style="margin-left:25px">
{% for item in averages %}
 <li>{{item.text}}</li>
{% endfor %}
</ol>

{% for voter in list.voters.all %}
<h3>{{ voter.name }}</h3>
<ol style="margin-left:25px">
  {% for vote in voter.votes.all %}
  <li>{{vote.item.text}}</li>
  {% endfor %}
</ol>
{% endfor %}

</div>


{% endblock %}

rankalist_web/apps/rankalist/templates/rankalist/thanks.html
{% extends "rankalist/base.html" %}
{% load uni_form_tags %}


{% block topbar %}{% endblock %}

{% block pageheader %}
  <h1>Thanks!</h1>
{% endblock %}
{% block maincontent %}
 
<div class="alert-message block-message info span9">
	
  <p><b>You're all set.</b> Whomever sent you this has a URL to see the results, ask them for it if you'd like to see everyone else's responses.</p>
</div>

{% endblock %}

{% block secondarycontent %}
<h3>Create a list</h3>
Want to create your own list for others to rank?  It's quick, easy, and free.<br/>
<br/>
<center><a href="/" class="btn success">Create your own list</a></center>

<br/><br/>

<h3>Do you Scrum?</h3>
Then check out <a href="http://www.scrumdo.com/">ScrumDo</a>, an agile project management website.

{% endblock %}

rankalist_web/apps/rankalist/templates/rankalist/vote.html
{% extends "rankalist/base.html" %}
{% load uni_form_tags %}


{% block topbar %}{% endblock %}

{% block extra_head %}
<script src="{{STATIC_URL}}vote_sort.js" type="text/javascript"></script>
{% endblock %}

{% block pageheader %}
<h2>{{ list.instructions }}</h2>
{% endblock %}

{% block maincontent %}



<div id="itemsToRank">
	<h3 id="stepInstruction" class="alert-message info span9">Click the item you think should rank the highest</h3>
	<ul id="items">
	  {% for item in list.items.all %}
	    <li item_id="{{item.id}}" class="itemToSort">{{item.text}}</li>
	  {% endfor %}
	</ul>
</div>


<div id="submitRanking" style="display:none">
	<a name="submitRank"></a>
	<h3 class="alert-message info span9">Submit Your Ranking</h3>
	<p>Almost done!  Tell us your name and click the button.</p>
	<form id="submitRank" class="uniForm" method="POST" action="">          
       <fieldset class="inlineLabels">
           <div id="div_id_name" class="ctrlHolder">
	            <label for="id_name" class="requiredField">
	                Name
	            </label>
				<div class="input">
		        <input id="id_name" type="text" class="textInput textinput" name="name" />
				</div>
		    </div>
		   {% csrf_token %}            
           <div class="form_block">
               <input type="hidden" name="action" value="create" />               
               <div class="actions">
                  <button id="createButton" class="btn primary" type="submit" >Submit Ranking</button>
               </div>
           </div>
       </fieldset>                        
   </form>
</div>
{% endblock %}

{% block secondarycontent %}
<div id="yourRanking" style="display:none" >
	<h3>Your ranking:</h3>

	<ol id="sorted">
	</ol>
	
	The top item is your highest rank.  You can drag them up or down if you change your mind. 
		You must rank all items to submit.
</div>








<script type="text/javascript" charset="utf-8">



	$(".itemToSort").click(function(){
		$(this).hide();

		$("#sorted").append("<li item_id='" + $(this).attr("item_id") + "' class='sortedItem'>" + $(this).text() + "</li>");
		$("#stepInstruction").text("Choose the next highest rank...");
		$("#yourRanking").fadeIn();
		if( $("#items li:visible").size() == 0 )
		{
			$("#itemsToRank").hide();
			$("#submitRanking").show();
		}
		$("#sorted").sortable({
					placeholder: "ui-state-highlight"
				});

	});
	
	
	
	$("#submitRank").submit(
		function() {
			if( $("#id_name").val() == "" )
			{
				alert("Please enter your name first.");
				return false;
			}
			
			var orders = "";
			
			$("#sorted li").each(function(){
				orders = orders + $(this).attr("item_id") + " ";
			});
			
			var input = $("<input>").attr("type", "hidden").attr("name", "orders").val(orders);
			$('#submitRank').append($(input));
			
		}
	);
</script>

{% endblock %}